@Controller=UserTask
@Url = {{Host_ShaoTempApi}}/{{Controller}}
@usertaskid  = 1

### 
POST {{Url}}/Query HTTP/1.1
Content-Type: application/json

{
  "page": 1,
  "pageSize": 10
}

### 
POST {{Url}}/Claim HTTP/1.1
Content-Type: application/json

{
  "promoteTaskSpecId": 5,
  "claimUser": {
    "mobile": "17600000001"
  }
}
### 
POST {{Url}}/Match HTTP/1.1
Content-Type: application/json

{
  "userTaskId": 3,
  "orderNo": "ssst"
}